BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = yes
STENO_ENABLE = yes
MOUSEKEY_ENABLE = no
NKRO_ENABLE = yes
MIDI_ENABLE = no
AUDIO_ENABLE = no
EXTRAKEY_ENABLE = yes

# below for minimize firmware size
CONSOLE_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLEt= no
API_SYSEX_ENABLE = no
KEY_LOCK_ENABLE = no
FAUXCLICKY_ENABLE = no

SRC += action_pseudo_lut.c
